# -*- coding: utf-8 -*-
"""Hotel Booking Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a-kyZPoSjhuZxjCQe9gu1-O5RWhU0W47

## <b> Have you ever wondered when the best time of year to book a hotel room is? Or the optimal length of stay in order to get the best daily rate? What if you wanted to predict whether or not a hotel was likely to receive a disproportionately high number of special requests? This hotel booking dataset can help you explore those questions!

## <b>This data set contains booking information for a city hotel and a resort hotel, and includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things. All personally identifying information has been removed from the data. </b>

## <b> Explore and analyze the data to discover important factors that govern the bookings. </b>
"""



"""## Importing required packages for data manipulation, cleaning and visualisation.

"""

# Important required librabries.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

file_path = ('/content/drive/MyDrive/Hotel Bookings.csv')
hotel_df= pd.read_csv(file_path)

hotel_df.info()

hotel_df.describe()

hotel_df.shape

"""## Count Null values"""

hotel_df.isnull().sum()

"""we have quite alot of NaN values in company, so removing company attribute will be a better idea from our given hotel dataset.

We are removing those column which are not useful for us
"""

#drop the columns which are not useful for us
hotel_df.drop(columns=['company','arrival_date_week_number','reservation_status_date'],inplace = True)

hotel_df.head(10)

"""# **Hotel Wise Analysis**

## Q.1 What is the percentage of bookings in each hotel?
"""

plt.rcParams['figure.figsize'] = 9,8
labels = hotel_df['hotel'].value_counts().index.tolist()
size = hotel_df['hotel'].value_counts().tolist()
explode = (0, 0.05)
colors = ['orange','lightblue']
plt.pie(size, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%',startangle=80, textprops={'fontsize': 14})

"""## Q.2 What is most preferred stay weekend night length in each hotel?"""

# Firstly filter the data
filter = hotel_df[hotel_df['is_canceled']==0]

hotel_df['total_nights'] = hotel_df['stays_in_weekend_nights'] + hotel_df['stays_in_week_nights']

stay = hotel_df.groupby(['total_nights', 'hotel']).agg('count').reset_index()
stay = stay.iloc[:, :3]
stay = stay.rename(columns={'is_canceled':'Number of stays'})

plt.figure(figsize = (15,5))
sns.barplot(x = 'total_nights', y = 'Number of stays',data= stay,hue='hotel')

"""City hotel is the most preferred hotel for weekend night rather than Resort hotel and customer stays number of time in City hotel.

# **Distribution Channel Wise Analysis**

## Q.1 Which is the most common channel for hotels booking?
"""

plt.figure(figsize=(40,5))
plt.subplot(1,2,1)
sns.countplot('market_segment',data = hotel_df)
plt.legend

"""Online TA(travel agent) is the most common channel for booking hotels compare than other hotels.

Here we can see that most number of guest are making reservation through TA/TO channels which is travel agent and tour operator.

## Q.2 Which distribution channel brings better revenue genrating deal for hotels?
"""

distribution_channel = hotel_df.groupby(['hotel'])['distribution_channel'].value_counts()

plt.rcParams['figure.figsize'] = (20,5)
distribution_channel.plot(kind = 'bar')
plt.title('Distribution channel')
plt.ylabel('no. of bookings')
plt.xlabel('channels')

"""*    Resort hotel has more revenue generating deals by direct and TA/TO channel.Resort hotel need to increase outreach on GDS to increase revenue.
*   GDS channel brings higher revnue generating deals for city hotel.City hotel can work to increase outreach on GDS channel to get more higher revenue generating deal.

# **Booking Cancellation Analysis**

## Q.1 Which hotel has higher booking cancellations rate?
"""

hotel_df['is_canceled'] = hotel_df.is_canceled.replace([1,0], ['canceled', 'not_canceled'])
canceled_data = hotel_df['is_canceled']
sns.countplot(canceled_data)
plt.figure(figsize=(3,5))

"""*    Blue colour stands for City hotel.
*   Orange colour stands for Resort hotel.

so far, we can conclude here that City hotel has higher booking cancellations rate than Resort hotel.

## **Univariate Analysis**

##Q.1 From which country most of the guest are coming?
"""

grp_by_country = hotel_df.groupby('country')
d2 = pd.DataFrame(grp_by_country.size()).rename(columns = {0:'no. of bookings'}).sort_values('no. of bookings', ascending = False)
d2 = d2[:10]
sns.barplot(x = d2.index, y = d2['no. of bookings'])
plt.show()

"""we can see in above graph that PRT,GBR,FRA are the countries whose number of bookings are respectively more than other countries.

## Q.2 Which room type is in most demand and which room type generates highest Average daily revenue?
"""

plt.figure(figsize=(40,5))
plt.subplot(1,2,1)
sns.countplot('assigned_room_type',data = hotel_df)

"""# **Time Wise Analysis**

#Q.1 What are the most busy month of hotels?
"""

plt.figure(figsize=(40,5))
plt.subplot(1,2,1)
sns.countplot('arrival_date_month',data = hotel_df,order = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December'])

"""##Q.2 which hotel charges highest Average Daily Rate?"""

adr_df = hotel_df.groupby('hotel')['adr'].agg(np.mean).reset_index().rename(columns = {'adr':'average_adr'})

plt.figure(figsize = (6,5))
sns.barplot(x = adr_df['hotel'], y = adr_df['average_adr'] )
plt.show()

"""City hotel charges more average daily rate because it is more in demand.And on the other hand Resort hotel charges less average daily rate as it is in less demand.

#**conclusion**


* Around 66.4% bookings are for City hotel and 33.6% are for Resort hotel,therfor City hotel is busier than Resort hotel.Also the overall Average Daily Rate of City hotel is slightly higher than Resort hotel.


* Mostly guests stay for less than 23 days in City hotel and for longer stays Resort hotel is preferred.

* Guests use diffrent channels for making booking out of which most preferred ways is TA/TO.

* City hotel charges more average daily rate because it is more in demand.And on the other hand Resort hotel charges less average daily rate as it is in less demand.

#                **THANK YOU**
"""